<?php
/**
 * Created by PhpStorm.
 * User: vuonglinh
 * Date: 1/2/17
 * Time: 14:46
 */

namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;

class ApiController extends Controller
{
    public function  initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}